<?php
/**
 *
 *
 *                 DO NOT EDIT THIS FILE
 *
 *
 * To customise your installation, edit "LocalSettings.php". If you make
 * changes here, they will be lost in the next upgrade of Hytools!
 *
 *
 */

// Hytools version number
$hyVersion = "2.3tsh1";

// Central sitenotice that appears at the top of every page
$hySiteNotice = "";

// Recipient of an email when an error occurs
$hyErrorRecipient = "someone@example.com";

// Sender of error email, can be anyone, depending on your server
$hyErrorSender = "noreply@example.com";

// Hard-coded path to directory that contains files available for anyone to download
$hyDownloadsFolder = "/home/hydriz/public_html/downloads";
