<?php

/*
    PLEASE DO NOT EDIT THIS FILE
    Please edit LocalSettings.php located in the
    main directory instead to overwrite the
    configuration found here.
    Configuration done here will be overwritten
    in the next upgrade!
*/

// Hytools version number
$hyVersion = "3.1";

// The website's name, override in LocalSettings.php
$hySitename = "Hytools";

// The full URL to the software's installation (no trailing slash please)
$hyServer = "https://toolserver.org/~hydriz";

// The global site notice to be displayed on top of pages
$hySitenotice = "";

// Set the logo of the software, override in LocalSettings.php
$hyLogo = "http://upload.wikimedia.org/wikipedia/en/b/bc/Wiki.png";

// Sets the skin the software uses
$hyUseSkin = "vector";
